elisa-tech/BASIL

Dockerfile-api
Dockerfile-app
docs/source/how_to_run_it.rst

Issue #15.
Adding Dockerfiles to support build and deployment via containers
Added a Container section in the documentation.

Adding Dockerfiles to support build and deployment via containers

---

api/api.py
app/src/app/Constants/constants.tsx
app/src/app/Custom/LeavesProgressBar.tsx
app/src/app/Dashboard/Form/APIForm.tsx
app/src/app/Dashboard/Modal/APICheckSpecModal.tsx
app/src/app/Dashboard/Modal/APIDeleteModal.tsx
app/src/app/Dashboard/Modal/APIExportSPDXModal.tsx
app/src/app/Dashboard/Modal/APIManageUserPermissionsModal.tsx
app/src/app/Dashboard/Modal/APIModal.tsx
app/src/app/Mapping/Mapping.tsx
app/src/app/Mapping/MappingListingTable.tsx
app/src/app/Mapping/MappingPageSection.tsx
app/src/app/Mapping/MappingViewSelect.tsx
app/src/app/Mapping/Modal/MappingCommentModal.tsx
app/src/app/Mapping/Modal/MappingDeleteModal.tsx
app/src/app/Mapping/Modal/MappingDetailsModal.tsx
app/src/app/Mapping/Modal/MappingForkModal.tsx
app/src/app/Mapping/Modal/MappingHistoryModal.tsx
app/src/app/Mapping/Modal/MappingJustificationModal.tsx
app/src/app/Mapping/Modal/MappingSwRequirementModal.tsx
app/src/app/Mapping/Modal/MappingTestCaseModal.tsx
app/src/app/Mapping/Modal/MappingTestSpecificationModal.tsx
app/src/app/Mapping/Modal/MappingUsageModal.tsx
app/src/app/Mapping/Modal/TestResultModal.tsx
app/src/app/Mapping/Modal/TestRunModal.tsx
app/src/app/Mapping/Search/TestCaseSearch.tsx
app/src/app/SSHKey/Modal/SSHKeyModal.tsx
db/models/api.py

Implemented default view selection per sw component #23.
Implemented an api endpoint to provide BASIL version.
Minor fixes in the app UI (like aria-label definition, missed alt definition for images)

Implemented default view selection per sw component.

---

api/api.py
app/src/app/Mapping/Mapping.tsx
app/src/app/Mapping/MappingListingTable.tsx
db/models/api.py
db/models/api_justification.py
db/models/api_sw_requirement.py
db/models/api_test_specification.py
db/models/justification.py
db/models/sw_requirement_sw_requirement.py
db/models/sw_requirement_test_case.py
db/models/sw_requirement_test_specification.py
db/models/test_specification_test_case.py

API problem: in the user notification update: there was no separator between sw component ids
UI problem: Mapping page section was nested under a PageSection with limited width
Removed logs from db/models
Removed console.log from app/

Fixes and debug print removal

---

.gitignore
api/api.py
app/src/app/AppLayout/AppLayout.tsx
app/src/app/Constants/constants.tsx
app/src/app/Dashboard/APIListingPageSection.tsx
app/src/app/Dashboard/APIListingTable.tsx
app/src/app/Dashboard/Dashboard.tsx
app/src/app/Dashboard/Form/APIForm.tsx
app/src/app/Mapping/Mapping.tsx
db/models/api.py
db/models/migration/sqlite_1_4_0.sql

#30 Implemented Api pagination.
The coverage is now calculated each time the api is opened and is cached in a field of the apis table in the basil database. That speed up the navigation in the api list page.

Implemented Api pagination.

---

app/src/app/Mapping/Mapping.tsx
app/src/app/Mapping/MappingListingTable.tsx
changelog.md
pyproject.toml

Test case gap highlight in case of direct mapping.

Test case gap highlight in case of direct mapping.

---

.github/workflows/build.yaml
Containerfile-api
Containerfile-app
docs/source/how_to_run_it.rst

Update Dockerfiles to Containerfiles
Update the documentation providing podman commands to build api and app containers.

Moving to podman

---

Containerfile-api-rpi
Containerfile-app
app/src/app/Constants/constants.tsx
misc/tmt_provision_podman.patch
misc/tmt_provision_podman_debian.patch
misc/tmt_provision_podman_debian_apt.patch
requirements.txt
run_demo_rpi.sh

Add a container file and a deployment example script to spin up a BASIL instance within a Raspberry Pi running Debian.

Add Container file and deployment script for Raspberry Pi

---

README.md

This PR is trying to solve the questions raised at #84

Add Differentiating factors to the README.md

---

app/src/app/Dashboard/Modal/APICheckSpecModal.tsx

Return message to the user on checking reference document mapping.

---

.flake8
.pre-commit-config.yaml
api/api.py
app/src/app/AppLayout/AppLayout.tsx
app/src/app/Constants/constants.tsx
app/src/app/Dashboard/Form/APIForm.tsx
app/src/app/Mapping/Form/DocumentForm.tsx
app/src/app/Mapping/Form/TestCaseForm.tsx
app/src/app/Mapping/Form/TestRunConfigForm.tsx
app/src/app/Mapping/MappingListingTable.tsx
app/src/app/UserFiles/Form/UserFilesAddForm.tsx
app/src/app/UserFiles/Form/UserFilesEditForm.tsx
app/src/app/UserFiles/Menu/UserFilesMenuKebab.tsx
app/src/app/UserFiles/Modal/UserFilesModal.tsx
app/src/app/UserFiles/UserFiles.tsx
app/src/app/UserFiles/UserFilesListing.tsx
app/src/app/routes.tsx
changelog.md
pyproject.toml

Add User Files section to upload and edit text files to user folder in the machine running the api project.
Refers to #47

Add User Files section

---

README.md
app/src/app/AppLayout/AppLayout.tsx

Adding link to Youtube channel and Matrix chat room
Solves #108

Add links to Youtube and Matrix

---

api/test/test_api.py
db/models/init_db.py
pyproject.toml

Fix existing API tests: add authentication and make them consistent with the current code base.

Fix existing API tests 

---

app/package-lock.json
app/package.json

Fix xlsx npm package vulnerability
Refers to #124

Fix xlsx npm package vulnerability

---

api/test/conftest.py
api/test/test_api_sw_requirement_mapping.py

Added more test cases for GET and POST methods of the ApiSwRequirementsMapping endpoint.
All test cases are based on description of https://github.com/elisa-tech/BASIL/issues/139
Test cases for PUT and DELETE are to be added later as a separate PR.

API app UT: improve coverage for GET and POST methods of ApiSwRequirementsMapping

---

api/api.py
api/api_utils.py
api/configs/testrun_plugin_presets.yaml
api/lava-job.yaml
api/testrun.py
api/testrun_lava.py
app/src/app/Constants/constants.tsx
app/src/app/Mapping/Form/TestRunConfigForm.tsx
app/src/app/Mapping/Modal/TestResultsModal.tsx
app/src/app/Mapping/Modal/TestRunModal.tsx
app/webpack.prod.js
docs/source/test_run.rst

Added a LAVA (Linaro Automated Validation Architecture) plugin to 
- trigger test run
- navigate and trace test external test runs to test cases
Refers to #137

Added LAVA Test run plugin

---

app/package-lock.json
app/package.json

Fix npm vulnerabilities

---

api/api.py
db/models/user.py

Prevent string manipulation in case of None object

---

app/src/app/Mapping/MappingListingTable.tsx

Fix Mapping page to work with long specification lines.

---

api/api.py
api/api_utils.py
api/configs/email_template.html
api/configs/settings.yaml
api/notifier.py
app/src/app/Login/Login.tsx
app/src/app/Signin/Signin.tsx
changelog.md

Support SMTP_SSL in email notifier. 
Provide better feedback to the user during login and password reset. 
Support of email template stored in api/configs.
Updated Changelog

Support SMTP_SSL in email notifier. Provide better feedback to the user during login and password reset

---

api/test/test_api_sw_requirement_mapping.py

Add missed test cases for PUT and DELETE.
Refers to #139

Added missed test cases for ApiSwRequirementsMapping

---

api/api.py
api/test/test_comment.py
app/src/app/Custom/CommentCard.tsx
app/src/app/Mapping/Form/CommentForm.tsx
app/src/app/Mapping/Form/TestRunConfigForm.tsx
app/src/app/Mapping/MappingPageSection.tsx
app/src/app/Mapping/Modal/MappingCommentModal.tsx
db/models/comment.py

- Extend comment api to edit/delete
- Implemented api test cases for comment endpoint
Refers to #166

Comment enhancements

---

api/api.py
api/test/test_sw_requirement_test_specification_mapping.py
db/db_orm.py

Upgraded the SwRequirementTestSpecificationsMapping permissions management
Added unit test for SwRequirementTestSpecificationsMapping
Refers to #172

SwRequirementTestSpecificationsMapping upgrade and tests
