elisa-tech/BASIL

api/README.md, db/README.md
Since pdm is creating a virtual environment with pdm install, we need to run the api backend and db creation with pdm run.
=> Fix in README: Usage of venvs via pdm run in READMEs

Dockerfile-app, docs/source/how_to_run_it.rst
Add a build argument in the Dockerfile-app to be able to specify the deployment application port building the app docker container.
=> Docker app port

app/src/app/Mapping/MappingListingTable.tsx, changelog.md, pyproject.toml
Gap was already hihglited in the section coverage on the left side of the mapping
=> Rever changes to Test Case gap implemented in v1.4

api/api.py, app/src/app/Dashboard/Modal/APICheckSpecModal.tsx, app/src/app/Mapping/Mapping.tsx, app/src/app/Mapping/MappingListingTable.tsx, app/src/app/Mapping/Menu/UnmappedMenuKebab.tsx, changelog.md, db/models/api.py, pyproject.toml
Show and manage unmapped Document. 
Avoid to increate the api version on case of last_coverage (field used as cached coverage value) changes. 
Fix warning of Document work items.
=> Show and manage unmapped Document. Fix Api updates.

app/src/app/Constants/constants.tsx
This issue prevented the definition of a custom API port at the time of the api container build.
=> Fix default API port in constants.tsx

db/README.md, db/db_orm.py, db/models/init_db.py, docs/source/e2e_testing.rst, docs/source/how_to_run_it.rst
Moving basil.db to db/sqlite3 to avoid issues with db/models updating BASIL to new versions. Refers to #62
=> Moving basil.db to db/sqlite3

Dockerfile-app, api/api.py, api/spdx_manager.py, app/src/app/Mapping/MappingPageSection.tsx, db/models/api.py, db/models/document.py, db/models/justification.py, db/models/sw_requirement.py, db/models/test_case.py, db/models/test_run.py, db/models/test_run_config.py, db/models/test_specification.py, requirements.txt
This MR is related to #63 and #64 
Extend spdx export to Document and Test Run.
Migrate to SPDX model3
UI change to export to SPDX from within a software component (not only from an entire library)
=> Extends spdx export to other work items and switch to SPDX Model3

api/api.py, api/spdx_manager.py, app/src/app/Mapping/Import/SwRequirementImport.tsx, app/src/app/Mapping/Modal/MappingSwRequirementModal.tsx
Adding a software requirement now a new tab is available in the modal view "import"
From here a user can select a json file exported from a BASIL instance and all software requirements will be listed in a table.
Each row will have a checkbox that allow users to select which work items to import.
Once selected and submitted the requirements will be generated and they will be available in the "Existing" tab (need to click search to refresh the list of requirements at the moment).
NOTE: We don't validate if an identical requirement already exists at this moment before creating a new work item. That validation is done in the manual insert.
=> Implement import of Software Requirements from json file exported from BASIL

Containerfile-api-debian, Containerfile-api-fedora
fedora api container missed the examples folders. 
Moved the copy of the files after the installation of the required packages to speedup the container build during development.
Execute the installation of python packages after the copy of the files because it needs the requirements.txt file.
=> Fix Containerfiles

app/src/app/Mapping/MappingListingTable.tsx, app/src/app/Mapping/MappingPageSection.tsx, app/src/app/Mapping/Modal/TestResultsModal.tsx, app/src/app/Mapping/Modal/TestRunModal.tsx
Triggering a new run (also re-running an existing one) we will be redirected to the Test Results modal view.
Refers to #89
=> Triggering a new run we will be redirected to the Test Results modal view

api/api.py, app/src/app/Constants/constants.tsx, app/src/app/Dashboard/Modal/APIManageUserPermissionsModal.tsx, app/src/app/Mapping/Modal/MappingTestCaseModal.tsx
A table is proposed with checkboxes to allow any software component owner to configure user permissions.
Moreover the UI provides a section to copy the permissions from a software component to another.
User can only assign permissions to user with role USER or ADMIN.
User with GUEST role can only be able to read contents.
If at least one restriction is assigned in read mode to a software component, by default BASIL will deny read access to a new GUEST user.
Refers to #70
=> Simplify user permission management 

api/api.py, api/notifier.py, api/settings.yaml, app/src/app/Admin/AdminSettings.tsx, app/src/app/Admin/Modal/AdminModal.tsx, app/src/app/AppLayout/AppLayout.tsx, app/src/app/AppLayout/HeaderToolbar.tsx, app/src/app/Constants/constants.tsx, app/src/app/Login/Login.tsx, app/src/app/Signin/Signin.tsx, app/src/app/User/AuthProvider.tsx, app/src/app/User/Modal/UserProfileModal.tsx, app/src/app/routes.tsx, db/models/init_db.py, db/models/migration/sqlite_1_6_3.sql, db/models/user.py
This PR solves the #60 
Added admin settings page to configure the smtp server and the APP endpoint.
Added frontend and backend support to:
- Reset password via email
- Edit user profile information such as username and password
The password reset works as following:
in the users table I added a field for a temporary password and a field for a token.
The temporary password is shared via email to the user and a link with the token is provided as part of the email to activate the new password. If the email is not wanted by the user nothing happen as the temporary password is not active. So user can continue to login with his original password.
If the reset is wanted, user can press the link in the email and temporary password will be activated.
If admin configure the APP endpoint correctly …
=> Reset password via email, user profile edit, admin settings

Containerfile-api-debian, Containerfile-api-fedora, docs/source/how_to_run_it.rst, run_demo.sh
run_demo.sh 
- is supporting an option -e to load an environment file to the api container
- is creating a volume to be mapped to user-files folder
Modified api container files to create the api/user-files folder
Updated documentation to describe the new run_demo.sh option -e
=> inject env file in the api container - volume for user-files folder

api/test/test_user_login.py
Added some unit tests for UserLogin endpoint of the API app.
The coverage is not 100% since I didn't test the "enable" logic and cache.
The PR is related to https://github.com/elisa-tech/BASIL/issues/32.
=> API app UT: add tests for UserLogin

Containerfile-app, app/webpack.prod.js, nginx.conf
Containerfile-app split build and deploy in 2 stages, to minimize final container size that is now 165 MB.
Serve the web application via nginx. 
Configure webpack production chunk sizes and other options.
Refers to #132
=> Container app optimizations

api/api.py, api/test/conftest.py, api/test/test_api_documents_mapping.py, api/test/test_api_sw_requirement_mapping.py
Add unit tests for ApiSwRequirementsMapping endpoint of the API app.
In addition, I've added 'offset' as a required field for ApiSwRequirementsMapping, since it is used by POST method.
The PR is related to https://github.com/elisa-tech/BASIL/issues/32.
=> API app UT: add tests for api<->SW requirement mapping

api/api.py, api/test/test_api_sw_requirement_mapping.py
Refactored a bit test cases for GET and POST methods of the ApiSwRequirementsMapping. Added more test cases for PUT and DELETE methods.
All test cases are based on https://github.com/elisa-tech/BASIL/issues/139
NOTE: The versioning of work items and mapping is not tested.
=> API app UT: improve coverage for PUT and DELETE methods of ApiSwRequirementsMapping

run_demo.sh
Building BASIL deployment images (api and app) with run_demo.sh, we will assign image tag based on the current BASIL version and commit hash. This way it will be simpler keep the application updated and understand the running version.
=> Add tag support for podman images

.github/workflows/build.yaml, requirements.txt
Add code coverage support for the API and collect the html folder into a tarball that will be exposed as an artifacts for further analysis.
=> CI - pytest coverage

app/src/app/AppLayout/AppLayout.tsx, app/src/app/Constants/constants.tsx
Add label to inform users about the availability of a newer release
It will ping github releases to check for a new release and will save the last release available in github in a cookie for 1 day to avoid multiple requests.
=> Add label to inform users about the availability of a newer release
